version: "3.9"
services:
  postgresdb:
    image: postgres:15.0
    container_name: coins-postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    command: ["sh", "-c", "env && docker-entrypoint.sh postgres"]
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - coins-pg-data:/var/lib/postgresql/data

  migrations:
    image: migrations
    build:
      context: ./
      dockerfile: docker/migrations.dockerfile
    command: [
      # DB waiter
      "/usr/local/bin/wait-for", "postgresdb:5432", "--",
      # dbmate auto migrations
      "/usr/local/bin/dbmate", "--url", "postgres://${DB_USER}:${DB_PASSWORD}@postgresdb:5432/${DB_NAME}?sslmode=disable", "up",
      # remove
      "rm", "-rf", "/db/migrations"
      ]
    env_file:
      - .env
    depends_on:
      - postgresdb

  coins:
    image: coins
    build:
      context: ./
      dockerfile: docker/coins.dockerfile
    env_file:
    - .env
    ports:
      - "8080:8080"
    depends_on:
      - migrations

volumes:
  coins-pg-data: {}