FROM golang:1.22.8 as builder

RUN apt-get update
# Install dbmate
RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
RUN chmod +x /usr/local/bin/dbmate

WORKDIR /usr/src/app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -o coins ./cmd

FROM alpine:latest

COPY --from=builder /usr/src/app/coins /coins
# COPY --from=builder /usr/src/app/coins ./.env

EXPOSE 8080

CMD ["/coins"]